export const NAV_LINKS = [
	{
		category: "Store",
		href: "/new-&-featured",
		product: [
			{
				title: "New and Featured",
				href: "/new-and-featured",
				items: [
					"Exlpore All Mac",
					"Mac",
					"iPad",
					"Mac Chip",
					"iPhone 16",
					"iChip ",
					"Mac Camera",
					"Night Visipn",
					"Apple TV",
				],
			},
			{
				title: "Shop Icons",
				href: "/shop-icons",
				items: [
					"Air Force 1",
					"Air Jordan 1",
					"Air Max",
					"Dunk",
					"Cortez",
					"Blazer",
					"Pegasus",
				],
			},
		],
	},
	{
		category: "Mac",
		href: "/men",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Apple All Mac",
					"iPad",
					"Mac",
					"Mac Chip",
					"iChip ",
					"iPhone 16",
					"Night Visipn",
					"Apple TV",
					"Mac Camera",
					,
				],
			},
			{
				title: "Jordan",
				href: "/jordan",
				items: [
					"All Jordan",
					"New Jordan",
					"Jo es",
					"hing",
					"Jorn Basall",
					"Jorda ifestyle",
				],
			},

			{
				title: "Shop By Brand",
				href: "/shop-by-brand",
				items: [
					"Nike Sportwear",
					"NikeLab",
					"Nike By You",
					"Jordan",
					"ACG",
					"NBA",
					"Nike SB",
				],
			},
		],
	},
	{
		category: "iPad",
		href: "/women",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Mac Chip",
					"Exlpore All Mac",
					"Mac",
					"Mac Camera",
					"iPad",
					"Apple TV",
					"iPhone 16",
					"iChip ",
					"Night Visipn",
				],
			},
		],
	},
	{
		category: "iPhone",
		href: "/kids",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Mac Camera",
					"Exlpore All Mac",
					"Mac",
					"Mac Chip",
					"iPhone 16",
					"iChip ",
					"Night Visipn",
					"Apple TV",
					"iPad",
				],
			},

			{
				title: "Accesories and Equipment",
				href: "/accesories-and-equipment",
				items: [
					"All Accesories and Equipment",
					"Bags and Backpacks",
					"Socks",
					"Hats and Headwear",
				],
			},
		],
	},
	{
		category: "Watch",
		href: "/sale",
		product: [
			{
				title: "Sale",
				href: "/sale",
				items: [
					"Mac Camera",
					"Mac Chip",
					"Exlpore All Mac",
					"iPhone 16",
					"iChip ",
					"Night Visipn",
					"Apple TV",
					"Mac",
					"iPad",
				],
			},
			{
				title: "Men's Sale",
				href: "/mens-sale",
				items: ["Shoes", "Clothing"],
			},
			{
				title: "Women's Sale",
				href: "/womens-sale",
				items: ["Shoes", "Clothing"],
			},
			{
				title: "Kids's Sale",
				href: "/kidss-sale",
				items: ["Shoes", "Clothing"],
			},
		],
	},
	{
		category: "Vision",
		href: "/nike-by-you",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Mac Camera",
					"iPhone 16",
					"Exlpore All Mac",
					"iChip ",
					"Mac Chip",
					"Night Visipn",
					"Apple TV",
					"Mac",
					"iPad",
				],
			},
			{
				title: "Kids By Age",
				href: "/kids-by-age",
				items: [
					"Older Kids (7 - 14 years)",
					"Younger Kids (4 - 7 years)",
					"Babies & Toddlers Kids (0 - 4 years)",
				],
			},
			,
		],
	},
	{
		category: "AirPods",
		href: "launch",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Night Visipn",
					"Mac Camera",
					"iPhone 16",
					"Exlpore All Mac",
					"iChip ",
					"Mac Chip",
					"Apple TV",
					"iPad",
					"Mac",
				],
			},

			{
				title: "Shop By Sport",
				href: "/shop-by-sport",
				items: [
					"Football",
					"Running",
					"Basketball",
					"Gym and Training",
					"Tennis",
				],
			},
		],
	},
	{
		category: "TV & Home",
		href: "/nike-by-you",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Night Visipn",
					"Mac Camera",
					"iPhone 16",
					"Exlpore All Mac",
					"iChip ",
					"Mac Chip",
					"Apple TV",
					"iPad",
					"Mac",
				],
			},

			{
				title: "Girls' Shoes",
				href: "/girls-shoes",
				items: [
					"All Shoes",
					"Older Girls (7 - 14 years)",
					"Younger Girls (4 - 7 years)",
					"Babies and Toddlers (0 - 4 years)",
					"Lifestyle",
					"Jordan",
					"Running",
					"Basketball",
					"Football",
					"Sandals and Slides",
				],
			},
		],
	},
	{
		category: "Entertainment",
		href: "/nike-by-you",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Night Visipn",
					"iPhone 16",
					"Exlpore All Mac",
					"iChip ",
					"Mac Camera",
					"Mac Chip",
					"Mac TV",
					"iPad",
					"Mac",
				],
			},
			{
				title: "Kids By Age",
				href: "/kids-by-age",
				items: [
					"Older Kids (7 - 14 years)",
					"Younger Kids (4 - 7 years)",
					"Babies & Toddlers Kids (0 - 4 years)",
				],
			},
			{
				title: "Boys' Shoes",
				href: "/boys-shoes",
				items: [
					"All Shoes",
					"Older Boys (7 - 14 years)",
					"Younger Boys (4 - 7 years)",
					"Babies and Toddlers (0 - 4 years)",
					"Lifestyle",
					"Jordan",
					"Running",
					"Basketball",
					"Football",
					"Sandals and Slides",
				],
			},
			{
				title: "Boys' Clothing",
				href: "/boys-clothing",
				items: [
					"Top and T-Shirts",
					"Hoodies and Sweatshirts",
					"Pants and Leggings",
					"Shorts",
					"All Boys' Clothing",
				],
			},
			{
				title: "Girls' Shoes",
				href: "/girls-shoes",
				items: [
					"All Shoes",
					"Older Girls (7 - 14 years)",
					"Younger Girls (4 - 7 years)",
					"Babies and Toddlers (0 - 4 years)",
					"Lifestyle",
					"Jordan",
					"Running",
					"Basketball",
					"Football",
					"Sandals and Slides",
				],
			},
			{
				title: "Girls' Clothing",
				href: "/girls-clothing",
				items: [
					"Top and T-Shirts",
					"Sports Bras",
					"Hoodies and Sweatshirts",
					"Pants and Leggings",
					"Shorts",
					"All Girls' Clothing",
				],
			},
			{
				title: "Accesories and Equipment",
				href: "/accesories-and-equipment",
				items: [
					"All Accesories and Equipment",
					"Bags and Backpacks",
					"Socks",
					"Hats and Headwear",
				],
			},
			{
				title: "Shop By Sport",
				href: "/shop-by-sport",
				items: [
					"Football",
					"Running",
					"Basketball",
					"Gym and Training",
					"Tennis",
				],
			},
		],
	},
	{
		category: "Accessories",
		href: "/nike-by-you",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Night Visipn",
					"iPhone 18",
					"iPhone 16",
					"Exlpore All Mac",
					"iChip ",
					"Mac Chip",
					"Apple TV",
					"iPad",
					"Mac",
				],
			},
			{
				title: "Kids By Age",
				href: "/kids-by-age",
				items: [
					"Older Kids (7 - 14 years)",
					"Younger Kids (4 - 7 years)",
					"Babies & Toddlers Kids (0 - 4 years)",
				],
			},
			{
				title: "Boys' Shoes",
				href: "/boys-shoes",
				items: [
					"All Shoes",
					"Older Boys (7 - 14 years)",
					"Younger Boys (4 - 7 years)",
					"Babies and Toddlers (0 - 4 years)",
					"Lifestyle",
					"Jordan",
					"Running",
					"Basketball",
					"Football",
					"Sandals and Slides",
				],
			},
		],
	},
	{
		category: "Support",
		href: "/nike-by-you",
		product: [
			{
				title: "Featured",
				href: "/featured",
				items: [
					"Night Visipn",
					"Mac Camera",
					"Exlpore All Mac",
					"iChip ",
					"Mac Chip",
					"iPhone 16",
					"Apple TV",
					"iPad",
					"Mac",
				],
			},
			{
				title: "Kids By Age",
				href: "/kids-by-age",
				items: [
					"Older Kids (7 - 14 years)",
					"Younger Kids (4 - 7 years)",
					"Babies & Toddlers Kids (0 - 4 years)",
				],
			},
		],
	},
];
